# Generated by Django 5.2.8 on 2025-11-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skills_learningskills_teachingskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
