# Generated by Django 5.2.8 on 2025-11-29 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='learningskills',
            constraint=models.UniqueConstraint(fields=('user', 'skills'), name='unique_learning_skill_per_user', violation_error_message='Skill already selected'),
        ),
    ]
